version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: coordsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  service_uploader:
    build:
      context: ./service_uploader
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: coordsdb
      APP_PORT: 8080

  service_postcodes:
    build:
      context: ./service_postcodes
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: coordsdb
      APP_PORT: 8001
